#!/usr/bin/env bash

# kubefin(1) is a utility to finalize namespace and others
# main source: 
# - https://medium.com/pareture/script-to-force-remove-kubernetes-namespace-finalizer-57b72bd9460d
# - https://kubernetes.io/blog/2021/05/14/using-finalizers-to-control-deletion/

# Copyright 2022 SysNet4Admin (Hoon Jo)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[[ -n $DEBUG ]] && set -x
set -eou pipefail
#IFS=$'\n\t'

check_prerequirements(){
  if yum list installed "jq" >/dev/null 2>&1; then
    true
  else
    yum install jq -y
  fi
}


finalize_namespace() {
  namespace=$1
  if [ -z "$namespace" ]
  then
    echo "This script requires a namespace argument input. None found. Exiting."
    exit 1
  fi
  kubectl get namespace $namespace -o json | jq '.spec = {"finalizers":[]}' > finalize_tmp.json
  kubectl proxy --port=8888 &
  sleep 5
  curl -H "Content-Type: application/json" -X PUT --data-binary @finalize_tmp.json http://localhost:8888/api/v1/namespaces/$namespace/finalize
  curl -X PUT localhost:8888/api/v1/namespaces/@namespace/finalize -H "Content-Type: application/json" --data-binary @finalize_tmp.json 
  pkill -9 -f "kubectl proxy"
  rm -rf finalize_tmp.json
}

clear_user() {
}

main() {
  # call finalize_namespace
  finalize_namespace "$1"

}

main "$@"

