#!/usr/bin/env bash

# kubefin(1) is a utility to finalize namespace and others
# main source: https://medium.com/pareture/script-to-force-remove-kubernetes-namespace-finalizer-57b72bd9460d

# Copyright 2022 SysNet4Admin (Hoon Jo)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[[ -n $DEBUG ]] && set -x
set -eou pipefail
#IFS=$'\n\t'


finalize_namespace() {
  namespace=$1
  if [ -z "$namespace" ]
  then
    echo "This script requires a namespace argument input. None found. Exiting."
    exit 1
  fi
  kubectl get namespace $namespace -o json | jq '.spec = {"finalizers":[]}' > /tmp/finalize_tmp.json
  kubectl proxy &
  sleep 5
  curl -H "Content-Type: application/json" -X PUT --data-binary /tmp/finalize_tmp.json http://localhost:8001/api/v1/namespaces/$namespace/finalize
  pkill -9 -f "kubectl proxy"
  rm /tmp/finalize_tmp.json
}

clear_user() {
}

main() {
  # call finalize_namespace
  finalize_namespace "$1"

}

main "$@"

